version: "2"
services:
  kibana1:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch1:9200
      SERVER_PORT: 5601
    ports: ['127.0.0.1:5601:5601']
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch1
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'transport.tcp.port=9300', 'http.port=9200',"ES_JAVA_OPTS=-Xms512m -Xmx512m"]
    ports:
    - '127.0.0.1:9200:9200'
